package bfst22.vector.Enum;

//Types of elements which are drawn on the MapCanvas
public enum WayType {
    COASTLINE, BEACH, RESIDENTIAL, INDUSTRIAL,
    GRASS, GRASSLAND, FARMLAND, PARK, WETLAND,
    WOOD, FOREST, MEADOW, SCRUB, CEMETERY, RECREATION_GROUND,
    GOLF, PITCH, WATER, BUILDING, UNKNOWN,
    HIGHWAY, MOTORWAY, TRUNK, PRIMARY, SECONDARY, TERTIARY, RESIDENTIAL_HIGHWAY, UNCLASSIFIED_HIGHWAY,
    LIVING_STREET, SERVICE, PEDESTRIAN, TRACK, BUS_GUIDEWAY, FOOTWAY, BRIDLEWAY, STEPS, CYCLEWAY, 
    ISLAND, BACKGROUND, RIVER, PATH;
}
